### ISSUE TITLE
Arm Build?

### ISSUE THREAD

**Issue by krionical** [hackerfactor/nuzzle#2]
Have any plans for an arm build or better yet, something like inclusion in entware for asusmerlin routers?

**Comment by hackerfactor** [comment]
Hi krionical,

Re: ARM build:
If the OS is linux/unix based and you have a C compiler, then it will work. No special code to build.

Re: inclusion in entware or routers?
No plans. The entware/OpenWRT systems I've previously played with have had almost zero horsepower. In my experience, the packet sniffers for OpenWRT often dropped packets and couldn't keep up with moderately high volume. As soon as you enable logging or real-time packet filtering, performance degrades too much.

**Comment by hackerfactor** [comment]
Hi krionical,

Re: ARM build:
If the OS is linux/unix based and you have a C compiler, then it will work. No special code to build.

Re: inclusion in entware or routers?
No plans. The entware/OpenWRT systems I've previously played with have had almost zero horsepower. In my experience, the packet sniffers for OpenWRT often dropped packets and couldn't keep up with moderately high volume. As soon as you enable logging or real-time packet filtering, performance degrades too much.

**Comment by hackerfactor** [comment]
No port to ARM needed.
No inclusion in routers.
